/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFiles;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.JTable;
import java.sql.*;
import java.sql.Date;
import java.lang.*;
import java.util.*;
import java.lang.*;
import java.time.LocalDate;
import javax.swing.JFrame;

/**
 *
 * @author Ananya
 */
public class ViewEmp extends javax.swing.JFrame {

    /**
     * Creates new form ViewEmp
     */
    public ViewEmp() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ShowEmp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EID", "STID", "FName", "LName", "Ph No", "Door No", "Street", "Area", "City", "State"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ShowEmp.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        ShowEmp.setText("Click to display Employees");
        ShowEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(ShowEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addComponent(Back)
                .addGap(47, 47, 47))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(ShowEmp))
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        AdminHome adminhome = new AdminHome();
        this.dispose();
        adminhome.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void ShowEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowEmpActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             //String query = "insert into PRODUCTS values('"+pid+"','"+brand+"','"+pname+"','"+mfg+"','"+exp"','"+cat+"','"+quantity+"','"+price+"')";
            // String query = "insert into PRODUCTS values("pid","brand","pname","mfg","exp","cat","quantity","price")";
            // String query = "INSERT INTO PRODUCTS VALUES('"+pid+"', '"+brand+"', '"+pname+"', '"+mfg+"', '"+exp+"', '"+cat+"', '"+quantity+"', '"+price+"')";
               
               

             Statement smt3=con.createStatement();
             String query = "SELECT * FROM EMPLOYEES";
             ResultSet rs=smt3.executeQuery(query);
             
             while(rs.next()){
                 
                
                    String EID =   rs.getString("EID");
                    String STID =   rs.getString("STID");
                    String fname = rs.getString("fname");
                    String lname= rs.getString("lname");
                    String phno = rs.getString("phno");
                    String doorno  = rs.getString("doorno");
                    String street = rs.getString("street");
                    String area = rs.getString("area");
                    String city = rs.getString("city");
                    String state = rs.getString("state");
            
                    
                    
                    
                    String tbData[] = {EID, STID, fname, lname, phno, doorno, street, area, city, state};
                    
                    DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
                    
                    tb1Model.addRow(tbData);
                    
                    
                    

            }
             con.close();
        }

    catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_ShowEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton ShowEmp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
